//! CLI argument parsing using clap

use clap::Parser as ClapParser;

/// Command-line interface for the Corten JavaScript Runtime
#[derive(ClapParser, Debug, Clone)]
#[command(name = "corten-js")]
#[command(version = "0.1.0")]
#[command(about = "JavaScript runtime written in Rust")]
pub struct Cli {
    /// JavaScript file to execute
    #[arg(short = 'f', long = "file")]
    pub file: Option<String>,

    /// Run interactive REPL
    #[arg(short = 'r', long = "repl")]
    pub repl: bool,

    /// Enable JIT compilation (enabled by default)
    #[arg(long = "jit", default_value_t = true)]
    pub jit: bool,

    /// Print generated bytecode
    #[arg(long = "print-bytecode")]
    pub print_bytecode: bool,

    /// Print AST
    #[arg(long = "print-ast")]
    pub print_ast: bool,
}

impl Cli {
    /// Create a new CLI instance with default values
    pub fn new() -> Self {
        Self {
            file: None,
            repl: false,
            jit: true,
            print_bytecode: false,
            print_ast: false,
        }
    }

    /// Create CLI with a file path
    pub fn with_file(file: String) -> Self {
        Self {
            file: Some(file),
            repl: false,
            jit: true,
            print_bytecode: false,
            print_ast: false,
        }
    }

    /// Create CLI for REPL mode
    pub fn with_repl() -> Self {
        Self {
            file: None,
            repl: true,
            jit: true,
            print_bytecode: false,
            print_ast: false,
        }
    }
}

impl Default for Cli {
    fn default() -> Self {
        Self::new()
    }
}
